-- DevBareun strict Row Level Security policies
-- Latest baseline: v1.3.9 Production Security
--
-- Supabase SQL Editor does not execute local include commands.
-- Apply this file by copying the SQL from:
-- database/2026_05_27_v139_production_security.sql
--
-- This pointer file is kept for repo compatibility with older setup notes.
