(function(){
  'use strict';
  const API = window.DevBareunSaaS || {};
  const SESSION_KEY='devbareun_supabase_session';
  const OWNER_KEY='devbareun_owner_email';
  const PLAN_KEY='devbareun_plan_code';
  const CREDIT_KEY='devbareun_credit_summary';
  const local = {
    projects: 'devbareun_local_projects', files: 'devbareun_local_files', analyses:'devbareun_local_analyses'
  };
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmtBytes=(b)=>{ if(!b && b!==0) return '—'; const u=['B','KB','MB','GB']; let n=Number(b),i=0; while(n>=1024&&i<u.length-1){n/=1024;i++;} return `${n.toFixed(i?1:0)} ${u[i]}`; };
  const toast=(msg)=>{ const el=document.createElement('div'); el.className='saas-toast'; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(),3000); };
  const read=(k)=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(_){return[]}}; const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  function session(){ try{return API.readSession?API.readSession():JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(_){return null} }
  function userEmail(){ const s=session(); return s?.user?.email || s?.email || localStorage.getItem(OWNER_KEY) || ''; }
  function setEmail(email){ if(email) localStorage.setItem(OWNER_KEY,email); }
  function planCode(){ return localStorage.getItem(PLAN_KEY)||'free'; }
  function nav(active){ const items=[['dashboard','Dashboard','dashboard.html'],['projects','Projects','projects.html'],['upload','Upload','upload.html'],['reports','Reports','reports.html'],['billing','Billing','billing.html'],['profile','Profile','profile.html']]; return `<div class="saas-nav">${items.map(i=>`<a class="${active===i[0]?'active':''}" href="${i[2]}">${i[1]}</a>`).join('')}<a href="index.html">Site</a></div>`; }
  function shell(page,title,subtitle,content){ document.body.classList.add('theme-dark'); document.body.innerHTML=`<main class="saas-shell"><div class="saas-container"><div class="saas-topbar"><a class="saas-brand" href="index.html"><img src="assets/devbareun-symbol-white.svg" onerror="this.style.display='none'" alt="DevBareun"><span>DevBareun</span></a>${nav(page)}</div><section class="saas-hero"><p class="saas-eyebrow">SaaS Platform</p><h1>${title}</h1><p>${subtitle}</p></section><div id="saas-app">${content}</div></div></main>`; }
  async function safe(fn,fallback){ try{return await fn()}catch(e){console.warn(e); return fallback} }
  async function credit(){ const email=userEmail(); if(!email) return {plan_code:planCode(),monthly_limit:0,used:0,remaining:0}; const data=await safe(()=>API.creditStatus?API.creditStatus(email):Promise.reject(),null); if(data?.credit_summary){localStorage.setItem(CREDIT_KEY,JSON.stringify(data.credit_summary)); return data.credit_summary;} try{return JSON.parse(localStorage.getItem(CREDIT_KEY)||'null')||{plan_code:planCode(),monthly_limit:0,used:0,remaining:0}}catch(_){return {plan_code:planCode(),monthly_limit:0,used:0,remaining:0}} }
  function localProjects(){ return read(local.projects); } function upsertProject(p){ const arr=localProjects().filter(x=>x.project_id!==p.project_id); arr.unshift(p); write(local.projects,arr); }
  function localFiles(projectId){ return read(local.files).filter(f=>!projectId || f.project_id===projectId).filter(f=>f.status!=='deleted'); } function addFile(f){ const arr=read(local.files); arr.unshift(f); write(local.files,arr); }
  function deleteLocalFile(id){ const arr=read(local.files).map(f=>f.file_id===id?{...f,status:'deleted'}:f); write(local.files,arr); }
  function localAnalyses(){ return read(local.analyses); } function addAnalysis(a){ const arr=localAnalyses(); arr.unshift(a); write(local.analyses,arr); }
  async function renderDashboard(){ shell('dashboard','Project dashboard','Protected project control workspace for saved projects, analysis credits, uploaded files and recent reports.',`<div class="saas-grid"><div class="saas-card"><p class="saas-eyebrow">Plan</p><div class="saas-kpi"><div><h3 id="planLabel">Loading</h3><p>Current subscription / access state.</p></div><span class="saas-badge" id="planBadge">—</span></div></div><div class="saas-card"><p class="saas-eyebrow">Credits</p><div class="saas-kpi"><div><strong id="creditRemain">—</strong><p>Remaining project analyses this cycle.</p></div><span class="saas-badge">monthly</span></div></div><div class="saas-card"><p class="saas-eyebrow">User</p><h3 id="userEmail">Guest</h3><p id="authHint">Login to protect projects and file history.</p></div><div class="saas-card wide"><h2>Recent projects</h2><div id="recentProjects" class="saas-list"></div></div><div class="saas-card"><h2>Quick actions</h2><div class="saas-actions"><a class="saas-btn primary" href="projects.html">Create project</a><a class="saas-btn secondary" href="upload.html">Upload files</a><a class="saas-btn secondary" href="billing.html">Credits</a></div></div></div>`); const c=await credit(); $('#planLabel').textContent=(c.plan_code||planCode()).toUpperCase(); $('#planBadge').textContent=c.monthly_limit?`${c.used||0}/${c.monthly_limit}`:'guest'; $('#creditRemain').textContent=c.remaining ?? '—'; $('#userEmail').textContent=userEmail()||'Guest access'; if(userEmail()) $('#authHint').textContent='Authenticated workspace session detected.'; const projects=localProjects(); $('#recentProjects').innerHTML=projects.length?projects.slice(0,5).map(p=>`<div class="saas-row"><div><strong>${esc(p.project_name)}</strong><br><small>${esc(p.project_id)} · ${esc(p.location||'No location')}</small></div><a class="saas-mini-btn" href="upload.html?project_id=${encodeURIComponent(p.project_id)}">Upload</a></div>`).join(''):`<div class="saas-empty">No local project history yet. Create a project to start a saved analysis workflow.</div>`; }
  function renderAuth(type){ const isReg=type==='register'; shell(type,isReg?'Create account':'Login',isReg?'Create a Plus/Pro workspace account while preserving the DevBareun design system.':'Access your protected DevBareun project workspace.',`<div class="saas-grid"><div class="saas-card wide"><form id="authForm" class="saas-form"><label>Email<input name="email" type="email" required placeholder="you@company.com"></label><label>Password<input name="password" type="password" required minlength="8" placeholder="Minimum 8 characters"></label>${isReg?`<label>Company name<input name="company_name" placeholder="Company name"></label><label>Contact person<input name="contact_person" placeholder="Contact person"></label>`:''}<div class="saas-actions"><button class="saas-btn primary" type="submit">${isReg?'Create account':'Login'}</button><a class="saas-btn secondary" href="${isReg?'login':'register'}.html">${isReg?'Already have account?':'Create account'}</a></div><p id="authStatus"></p></form></div><div class="saas-card"><h3>Protected access</h3><p>Dashboard, project history, uploaded files and report records are linked to the authenticated user session.</p></div></div>`); $('#authForm').addEventListener('submit',async(e)=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const payload=Object.fromEntries(fd.entries()); $('#authStatus').textContent='Processing...'; try{ const res= isReg ? await API.register(payload.email,payload.password,payload) : await API.login(payload.email,payload.password); setEmail(payload.email); $('#authStatus').textContent='Success. Redirecting to dashboard...'; toast('Session saved'); setTimeout(()=>location.href='dashboard.html',700); }catch(err){ $('#authStatus').textContent=`Could not authenticate: ${err.message}. If Supabase is not configured, use Single Project pilot flow.`; } }); }
  function renderProjects(){ shell('projects','Projects','Create and manage construction projects with Project IDs, ownership and analysis history.',`<div class="saas-grid"><div class="saas-card wide"><h2>Create project</h2><form id="projectForm" class="saas-form"><label>Project name<input name="project_name" required placeholder="Project name"></label><label>Location<input name="location" placeholder="City / site"></label><label>Contractor<input name="contractor"></label><label>Client<input name="client"></label><label>Contract value<input name="contract_value" type="number" step="0.01"></label><label>Currency<select name="currency"><option>AZN</option><option>USD</option><option>EUR</option></select></label><label>Control package<select name="analysis_type"><option value="all">Full Project Control</option><option value="schedule">Schedule Recovery</option><option value="cost">Cost & Payment Control</option><option value="material">Material Continuity</option><option value="risk">Risk & Decisions</option></select></label><button class="saas-btn primary" type="submit">Create project</button><p id="projectStatus"></p></form></div><div class="saas-card"><h2>Project history</h2><div id="projectList" class="saas-list"></div></div></div>`); const render=()=>{$('#projectList').innerHTML=localProjects().length?localProjects().map(p=>`<div class="saas-row"><div><strong>${esc(p.project_name)}</strong><br><small>${esc(p.project_id)} · ${esc(p.analysis_type||'all')}</small></div><a class="saas-mini-btn" href="upload.html?project_id=${encodeURIComponent(p.project_id)}">Files</a></div>`).join(''):'<div class="saas-empty">No projects yet.</div>';}; render(); $('#projectForm').addEventListener('submit',async(e)=>{e.preventDefault(); const payload=Object.fromEntries(new FormData(e.currentTarget).entries()); payload.owner_email=userEmail()||payload.owner_email||'guest@devbareun.local'; if(payload.contract_value) payload.contract_value=Number(payload.contract_value); $('#projectStatus').textContent='Creating...'; const data=await safe(()=>API.createProject(payload),null); const p=data?.project||{...payload,project_id:`DB-PRJ-LOCAL-${Date.now().toString().slice(-6)}`,created_at:new Date().toISOString()}; upsertProject(p); $('#projectStatus').textContent=`Created ${p.project_id}`; render(); toast('Project created'); }); }
  function renderUpload(){
    const url=new URL(location.href);
    let projectId=url.searchParams.get('project_id') || localProjects()[0]?.project_id || '';
    shell('upload','Upload files','Upload Excel, PDF and Word files to secure storage. File names stay visible, each item can be removed before analysis.',`<div class="saas-grid"><div class="saas-card wide"><h2>Upload workspace</h2><form id="uploadMeta" class="saas-form"><label>Project<select id="projectSelect"></select></label><label>Control package<select id="analysisType"><option value="all">Full Project Control</option><option value="schedule">Schedule Recovery</option><option value="cost">Cost & Payment Control</option><option value="material">Material Continuity</option><option value="risk">Risk & Decisions</option></select></label></form><div class="saas-drop"><input id="fileInput" type="file" multiple accept=".xlsx,.xls,.csv,.pdf,.doc,.docx"><p>Select multiple files. Names, size and type will appear below.</p></div><div id="fileList" class="saas-file-list"></div><div class="saas-actions"><button id="createAnalysis" class="saas-btn primary">Upload and create analysis</button><button id="clearLocal" class="saas-btn secondary">Clear selected files</button></div><p id="uploadStatus"></p></div><div class="saas-card"><h2>Required flow</h2><p>Files are uploaded to private storage before analysis. Project ID, File ID and Analysis ID stay separate for traceability.</p><div id="uploadSummary" class="saas-list"></div></div></div>`);
    const projects=localProjects();
    $('#projectSelect').innerHTML=projects.length?projects.map(p=>`<option value="${esc(p.project_id)}" ${p.project_id===projectId?'selected':''}>${esc(p.project_id)} — ${esc(p.project_name)}</option>`).join(''):'<option value="">Create a project first</option>';
    let selected=[];
    const render=()=>{
      projectId=$('#projectSelect').value;
      const saved=localFiles(projectId);
      const all=[...selected.map((f,i)=>({temp:true,file:f,id:`TEMP-${i}`,original_name:f.name,size_bytes:f.size,content_type:f.type,upload_progress:f._progress||0,status:f._status||'selected'})),...saved];
      $('#fileList').innerHTML=all.length?all.map((f,i)=>`<div class="saas-file"><div><div class="saas-file-title">${esc(f.original_name||f.file?.name)}</div><div class="saas-file-meta">${esc(f.file_id||f.id)} · ${fmtBytes(f.size_bytes||f.file?.size)} · ${esc(f.content_type||f.file?.type||'file')} · ${esc(f.status||'ready')}</div>${f.upload_progress?`<div class="saas-progress"><span style="width:${Math.min(100,Math.max(0,Number(f.upload_progress)||0))}%"></span></div>`:''}</div><button class="saas-btn danger" data-remove="${f.temp?'temp:'+i:f.file_id}">Remove</button></div>`).join(''):'<div class="saas-empty">No files selected yet.</div>';
      $('#uploadSummary').innerHTML=`<div class="saas-row"><span>Selected files</span><strong>${selected.length}</strong></div><div class="saas-row"><span>Uploaded file records</span><strong>${saved.length}</strong></div><div class="saas-row"><span>Ready for analysis</span><strong>${saved.filter(f=>['uploaded','metadata_recorded','local_record'].includes(f.status)).length}</strong></div>`;
    };
    $('#fileInput').addEventListener('change',e=>{selected=[...selected,...Array.from(e.target.files||[])]; e.target.value=''; render();});
    $('#fileList').addEventListener('click',async e=>{const key=e.target?.dataset?.remove; if(!key)return; if(key.startsWith('temp:')) selected.splice(Number(key.split(':')[1]),1); else { await safe(()=>API.deleteFile?API.deleteFile(key):Promise.resolve(),null); deleteLocalFile(key); } render();});
    $('#clearLocal').onclick=()=>{selected=[]; render();};
    $('#projectSelect').onchange=render;
    $('#createAnalysis').onclick=async()=>{
      if(!projectId){toast('Create a project first');return;}
      $('#uploadStatus').textContent='Uploading files to secure storage...';
      const uploadedIds=[];
      for(const file of selected){
        file._status='creating signed URL'; file._progress=3; render();
        let row=null;
        const payload= await safe(()=>API.createUploadUrl(projectId,file),null);
        if(payload?.file && API.uploadToSignedUrl){
          row=payload.file;
          file._status='uploading';
          await API.uploadToSignedUrl(payload,file,(pct)=>{file._progress=pct; render();});
          row={...row,status:'uploaded',upload_progress:100};
        } else {
          row={file_id:`DB-FILE-LOCAL-${Date.now().toString().slice(-6)}-${uploadedIds.length+1}`,project_id:projectId,original_name:file.name,size_bytes:file.size,content_type:file.type,status:'local_record'};
        }
        addFile(row); uploadedIds.push(row.file_id);
      }
      const existing=localFiles(projectId).filter(f=>f.status!=='deleted').map(f=>f.file_id);
      const analysisPayload={project_id:projectId,uploaded_file_ids:[...new Set([...existing,...uploadedIds])],analysis_type:$('#analysisType').value,owner_email:userEmail()||'guest@devbareun.local',consume_credit_now:false};
      $('#uploadStatus').textContent='Creating analysis record...';
      const data=await safe(()=>API.api?API.api('/api/analysis/create',{method:'POST',body:JSON.stringify(analysisPayload)}):Promise.reject(),null);
      const a=data?.analysis||{analysis_id:`DB-ANL-LOCAL-${Date.now().toString().slice(-6)}`,project_id:projectId,...analysisPayload,status:'local_ready',created_at:new Date().toISOString()};
      addAnalysis(a); selected=[]; $('#uploadStatus').textContent=`Analysis record ready: ${a.analysis_id}`; render(); toast('Analysis record created');
    };
    render();
  }
  function renderBilling(){ shell('billing','Billing and credits','Select Single Project, Plus or Pro and track monthly project analysis credits.',`<div class="saas-plan-cards"><div class="saas-plan"><span class="saas-badge">One-time</span><h2>Single Project</h2><p>For one-time construction project review.</p><ul><li>1 project analysis</li><li>PDF report</li><li>Secure result link</li></ul><button class="saas-btn primary" data-plan="single">Analyze One Project</button></div><div class="saas-plan featured"><span class="saas-badge">5/month</span><h2>Plus</h2><p>For small teams.</p><ul><li>5 project analyses/month</li><li>PDF + basic Excel</li><li>History</li></ul><button class="saas-btn primary" data-plan="plus">Start Plus</button></div><div class="saas-plan"><span class="saas-badge">20/month</span><h2>Pro</h2><p>For construction companies and PMO teams.</p><ul><li>20 analyses/month</li><li>Advanced dashboard</li><li>A4/A3 print</li></ul><button class="saas-btn primary" data-plan="pro">Start Pro</button></div></div><div class="saas-card full" style="margin-top:14px"><h2>Credit status</h2><div id="creditBox"></div></div>`); credit().then(c=>{$('#creditBox').innerHTML=`<div class="saas-row"><span>Plan</span><strong>${esc(c.plan_code||planCode())}</strong></div><div class="saas-row"><span>Used</span><strong>${c.used??0}</strong></div><div class="saas-row"><span>Remaining</span><strong>${c.remaining??0}</strong></div>`}); $$('[data-plan]').forEach(b=>b.onclick=async()=>{const plan=b.dataset.plan; localStorage.setItem(PLAN_KEY,plan); const fn=plan==='single'?API.createOneTimeCheckout:API.createSubscriptionCheckout; const data=await safe(()=>fn?fn({plan_code:plan,customer_email:userEmail()||undefined,success_url:location.origin+'/payment-success.html',cancel_url:location.origin+'/payment-failed.html'}):Promise.reject(),null); if(data?.url) location.href=data.url; else toast(`${plan.toUpperCase()} selected. Configure Stripe to redirect to checkout.`);}); }
  function renderReports(){ shell('reports','Reports','Every analysis can have a separate Analysis ID, Result ID, PDF, Excel and print-ready output.',`<div class="saas-card full"><h2>Analysis history</h2><div id="analysisList" class="saas-table-wrap"></div></div>`); const rows=localAnalyses(); $('#analysisList').innerHTML=rows.length?`<table class="saas-table"><thead><tr><th>Analysis ID</th><th>Project</th><th>Package</th><th>Files</th><th>Status</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(a.analysis_id)}</td><td>${esc(a.project_id)}</td><td>${esc(a.analysis_type)}</td><td>${(a.uploaded_file_ids||[]).length}</td><td>${esc(a.status)}</td></tr>`).join('')}</tbody></table>`:'<div class="saas-empty">No analysis records yet.</div>'; }
  function renderProfile(){ shell('profile','Profile and company','Manage user and company identity used in project analysis reports.',`<div class="saas-grid"><div class="saas-card wide"><form class="saas-form" id="profileForm"><label>Email<input name="email" type="email" value="${esc(userEmail())}" placeholder="you@company.com"></label><label>Company name<input name="company_name" value="${esc(localStorage.getItem('devbareun_company_name')||'')}"></label><label>Contact person<input name="contact_person" value="${esc(localStorage.getItem('devbareun_contact_person')||'')}"></label><label>Phone<input name="phone" value="${esc(localStorage.getItem('devbareun_phone')||'')}"></label><button class="saas-btn primary">Save profile</button></form></div><div class="saas-card"><h2>Session</h2><p>${esc(userEmail()||'Guest')}</p><button id="logout" class="saas-btn secondary">Logout / clear session</button></div></div>`); $('#profileForm').onsubmit=e=>{e.preventDefault(); const v=Object.fromEntries(new FormData(e.currentTarget).entries()); setEmail(v.email); ['company_name','contact_person','phone'].forEach(k=>localStorage.setItem('devbareun_'+k,v[k]||'')); toast('Profile saved');}; $('#logout').onclick=()=>{API.clearSession&&API.clearSession(); localStorage.removeItem(OWNER_KEY); toast('Session cleared');}; }
  function renderSettings(){ shell('settings','Settings','Configure reporting defaults, print preferences and dashboard behavior.',`<div class="saas-card full"><form class="saas-form" id="settingsForm"><label>Default print size<select name="print"><option>A4</option><option>A3</option></select></label><label>Default report language<select name="lang"><option value="en">English</option><option value="az">Azərbaycanca</option></select></label><label>Default currency<select name="currency"><option>AZN</option><option>USD</option><option>EUR</option></select></label><button class="saas-btn primary">Save settings</button></form></div>`); $('#settingsForm').onsubmit=e=>{e.preventDefault(); const v=Object.fromEntries(new FormData(e.currentTarget).entries()); localStorage.setItem('devbareun_saas_settings',JSON.stringify(v)); toast('Settings saved');}; }
  function renderAdmin(){ shell('admin','Admin panel','Operational overview for users, companies, projects, payments, reports and usage.',`<div class="saas-grid" id="adminGrid"><div class="saas-card full">Loading admin overview...</div></div>`); safe(()=>API.adminOverview(),null).then(data=>{const d=data||{}; $('#adminGrid').innerHTML=['users','companies','projects','guest_orders','analysis_results','payments'].map(k=>`<div class="saas-card"><p class="saas-eyebrow">${k.replaceAll('_',' ')}</p><strong style="font-size:34px">${d[k]??0}</strong></div>`).join('');}); }
  function renderGuest(){ shell('guest-result','Secure guest result','Temporary paid result links are validated by backend token and expiry rules.',`<div class="saas-card full"><form id="guestForm" class="saas-form"><label>Guest result token<input name="token" placeholder="Paste token from secure link"></label><button class="saas-btn primary">Open guest result</button><p id="guestStatus"></p></form></div>`); $('#guestForm').onsubmit=async e=>{e.preventDefault(); const token=new FormData(e.currentTarget).get('token'); $('#guestStatus').textContent='Checking token...'; const data=await safe(()=>API.api(`/api/guest-result/${encodeURIComponent(token)}`),null); $('#guestStatus').textContent=data?`Project: ${data.project?.project_id||'available'}`:'Token could not be validated.';}; }
  async function init(){ const page=document.body.dataset.saasPage || location.pathname.split('/').pop().replace('.html','') || 'dashboard'; if(page==='login') return renderAuth('login'); if(page==='register') return renderAuth('register'); if(page==='dashboard') return renderDashboard(); if(page==='projects') return renderProjects(); if(page==='upload') return renderUpload(); if(page==='billing'||page==='checkout') return renderBilling(); if(page==='reports') return renderReports(); if(page==='profile') return renderProfile(); if(page==='settings') return renderSettings(); if(page==='admin') return renderAdmin(); if(page==='guest-result') return renderGuest(); }
  document.addEventListener('DOMContentLoaded',init);
})();
